version: 2

updates:
  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "phanivikranth"
    assignees:
      - "phanivikranth"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "python"

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "phanivikranth"
    assignees:
      - "phanivikranth"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"

  # Root package.json (if any)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "phanivikranth"
    assignees:
      - "phanivikranth"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "root"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "phanivikranth"
    assignees:
      - "phanivikranth"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "backend"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "phanivikranth"
    assignees:
      - "phanivikranth"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: 1
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "phanivikranth"
    assignees:
      - "phanivikranth"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"
