apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-filter-backend
  namespace: word-filter-app
  labels:
    app: word-filter-backend
    component: api
    cloud-provider: civo
    environment: minimal
spec:
  replicas: 1  # Just 1 replica for testing
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: word-filter-backend
  template:
    metadata:
      labels:
        app: word-filter-backend
        component: api
        cloud-provider: civo
        environment: minimal
    spec:
      containers:
      - name: backend
        image: phanivikranth/word-filter-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: http
        
        # Minimal environment setup
        env:
        - name: PORT
          value: "8001"
        - name: HOST
          value: "0.0.0.0"
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: CORS_ORIGINS
          value: "*"
        
        # Use local file storage for minimal setup (no object store required)
        - name: USE_LOCAL_STORAGE
          value: "true"
        - name: WORDS_FILE_PATH
          value: "/app/words.txt"
        
        # Minimal resource requirements
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Basic health checks
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # Basic security
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
      
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: word-filter-backend
  namespace: word-filter-app
  labels:
    app: word-filter-backend
    component: api
    cloud-provider: civo
    environment: minimal
spec:
  type: NodePort  # Use NodePort for minimal setup
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
    # nodePort will be automatically assigned (30000-32767)
  selector:
    app: word-filter-backend
