name: Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Simple Test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test step
      run: |
        echo "Hello from GitHub Actions!"
        echo "Current branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
